language: node_js

node_js:
    - stable

services:
    - docker 

cache:
    directories:
    - node_modules

before_install:
    - docker build -t chiefbee/client-test -f ./client/Dockerfile.dev ./client
 
script:
    - docker run -e CI=true chiefbee/client-test npm test

after_success:
    - docker build -t chiefbee/multi-containers-client ./client
    - docker build -t chiefbee/multi-containers-server ./server
    - docker build -t chiefbee/multi-containers-nginx ./nginx
    - docker build -t chiefbee/multi-containers-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push chiefbee/multi-containers-client
    - docker push chiefbee/multi-containers-server
    - docker push chiefbee/multi-containers-nginx
    - docker push chiefbee/multi-containers-worker

deploy:
    verbose: true
    skip_cleanup: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-containers"
    env: "MultiContainers-env"
    bucket_name: "elasticbeanstalk-us-east-1-096846156347"
    bucket_path: "multi-containers"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY